### ISSUE TITLE
Bad code style: Nested maps

### ISSUE THREAD

**Issue by hanssv** [aeternity/aepp-sophia-examples#29]
I've had a look at some of the examples and discovered code that looks inefficient/unnecessarily long/unnecessarily complex:

In some places there seem to be a struggle to handle nested maps efficiently,
there are helper functions with names like `create_nested_map_if_not_exists`.

A canonical example could be:
```
  record state = { x : map(int, map(int, int)) }

  function add(k1 : int, k2 : int, v : int) =
    put(state{ x[k1][k2] = v })
```

This will fail if there isn't already a map for `k1` in `x` - the reason being
that there will be a lookup of `x[k1]` that fails - if that is not the behavior
that is intended but instead you'd rather add an empty map and then add `k2` to
this map this can be achieved like this:

```
  record state = { x : map(int, map(int, int)) }

  function add(k1 : int, k2 : int, v : int) =
    put(state{ x[k1 = {}][k2] = v })
```

Note the `k1 = {}`, this says that "if `k1` is not a member of the map the
default value is `{}` (the empty map). And we proceed by inserting `k2` in this
empty map.

**Comment by marc0olo** [comment]
I guess I removed the examples where this was the case in #62. I looked at the remaining contracts and couldn't find places where this should bechanged.
