### ISSUE TITLE
Add Auction Smart Contract

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-sophia-examples#3]
child of #2

As a user I want to be able to host and participate in Auction, so smart contracts for this can be implemented in Sophia

**Comment by maptuhec** [comment]
This won't be implemented, So I am closing the issue

**Comment by mradkov** [comment]
Maybe we can generalize the auction functionality from the drone graffiti app? @thepiwo

**Comment by thepiwo** [comment]
It could be, but has a very specific use-case. I'll give it some thoughts

**Comment by mradkov** [comment]
Otherwise I've implemented basic auction in the past here: https://github.com/mradkov/auction-aepp/blob/master/contracts/Auction.aes

Maybe I can adjust it a bit and make a PR.

**Comment by thepiwo** [comment]
What I don't like about this as done in solidity approach is that participants always have to withdraw manually...

**Comment by mradkov** [comment]
I think this is always a better approach from a security perspective - at least in Solidity this is an issue.

> The use of the Pull over Push pattern is a good way to mitigate some of the quirks that come with Solidity when sending ether, especially when performing multiple transfers at once.
